# Generated by Django 3.1.7 on 2021-02-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ManyToManyField(related_name='authors_question', to='usertests.QuestionAuthor', verbose_name='Автор вопроса'),
        ),
    ]
